# Generated by Django 5.2.2 on 2025-06-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cardcategory_playercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='batting_throws',
            field=models.CharField(default='R/R', max_length=3),
        ),
        migrations.AddField(
            model_name='playercard',
            name='mlb_url',
            field=models.URLField(default='https://www.mlb.com/dodgers'),
        ),
        migrations.AddField(
            model_name='playercard',
            name='number',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
