# Generated by Django 5.2.3 on 2025-06-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_playercard_batting_throws_playercard_mlb_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercard',
            name='category',
        ),
        migrations.RemoveField(
            model_name='playercard',
            name='batting_throws',
        ),
        migrations.RemoveField(
            model_name='playercard',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='playercard',
            name='mlb_url',
        ),
        migrations.RemoveField(
            model_name='playercard',
            name='price',
        ),
        migrations.RemoveField(
            model_name='playercard',
            name='rarity',
        ),
        migrations.RemoveField(
            model_name='playercard',
            name='team',
        ),
        migrations.RemoveField(
            model_name='playercard',
            name='year',
        ),
        migrations.DeleteModel(
            name='CardCategory',
        ),
    ]
